name: Test_Automation
on: push

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
     - name: Get checkout
       uses: actions/checkout@v4
     - name: Get python
       uses: actions/setup-python@v4
       with:
         python-version: "3.11.2"
     - name: Get Chrome
       run: sudo apt-get install google-chrome-stable
     - name: Get requirements
       run: pip3 install -r requirements.txt
     - name: RUN TEST
       run: pytest
     
       
